import { useState } from 'react'
import MyTable from './components/MyTable';
import './App.css'

function App() {
 
  return (
    <>
      <div className='main'>
       <MyTable tableSchema={tableSchema} tableData={tableData} />
     </div>
    </>
  )
}

export default App
const tableSchema = [
  { field: 'id', headerName: 'ID', width: 70  },
  { field: 'name', headerName: 'Name' ,  width: 230},
  { field: 'status', headerName: 'Status' , width: 130},
  { field: 'role', headerName: 'Role', width: 130 },
  { field: 'email', headerName: 'Email', width: 70},
];

const tableData = [
  { id: 1, name: 'John Doe', status: 'Working', role: 'Software Engineer', email: 'john.doe@example.com' },
  { id: 2, name: 'Jane Smith', status: 'Working', role: 'Data Analyst', email: 'jane.smith@example.com' },
  { id: 3, name: 'Alice Johnson', status: 'Working', role: 'UI Designer', email: 'alice.johnson@example.com' },
  { id: 4, name: 'Bob Williams', status: 'Working', role: 'Product Manager', email: 'bob.williams@example.com' },
  { id: 5, name: 'Charlie Brown', status: 'Working', role: 'QA Tester', email: 'charlie.brown@example.com' },
  { id: 6, name: 'Emily Davis', status: 'Working', role: 'DevOps Engineer', email: 'emily.davis@example.com' },
  { id: 7, name: 'George Garcia', status: 'Working', role: 'Software Engineer', email: 'george.garcia@example.com' },
  { id: 8, name: 'Hannah Rodriguez', status: 'Working', role: 'Data Analyst', email: 'hannah.rodriguez@example.com' },
  { id: 9, name: 'Isaac Wilson', status: 'Working', role: 'UI Designer', email: 'isaac.wilson@example.com' },
  { id: 10, name: 'Jack Martinez', status: 'Working', role: 'Product Manager', email: 'jack.martinez@example.com' },
  { id: 11, name: 'Katie Anderson', status: 'Working', role: 'QA Tester', email: 'katie.anderson@example.com' },
  { id: 12, name: 'Liam Taylor', status: 'Working', role: 'DevOps Engineer', email: 'liam.taylor@example.com' },
  { id: 13, name: 'Mia Thomas', status: 'Working', role: 'Software Engineer', email: 'mia.thomas@example.com' },
  { id: 14, name: 'Noah Jackson', status: 'Working', role: 'Data Analyst', email: 'noah.jackson@example.com' },
  { id: 15, name: 'Olivia White', status: 'Working', role: 'UI Designer', email: 'olivia.white@example.com' },
  { id: 16, name: 'Peter Harris', status: 'Working', role: 'Product Manager', email: 'peter.harris@example.com' },
  { id: 17, name: 'Quinn Martin', status: 'Working', role: 'QA Tester', email: 'quinn.martin@example.com' },
  { id: 18, name: 'Ryan Thompson', status: 'Working', role: 'DevOps Engineer', email: 'ryan.thompson@example.com' },
  { id: 19, name: 'Sophia Garcia', status: 'Working', role: 'Software Engineer', email: 'sophia.garcia@example.com' },
  { id: 20, name: 'Steven Perez', status: 'Working', role: 'Data Analyst', email: 'steven.perez@example.com' },
  { id: 21, name: 'Tyler Robinson', status: 'Working', role: 'UI Designer', email: 'tyler.robinson@example.com' },
  { id: 22, name: 'Ursula Clark', status: 'Working', role: 'Product Manager', email: 'ursula.clark@example.com' },
  { id: 23, name: 'Vincent Lewis', status: 'Working', role: 'QA Tester', email: 'vincent.lewis@example.com' },
  { id: 24, name: 'Wendy Lee', status: 'Working', role: 'DevOps Engineer', email: 'wendy.lee@example.com' },
  { id: 25, name: 'Xavier Hall', status: 'Working', role: 'Software Engineer', email: 'xavier.hall@example.com' },
  { id: 26, name: 'Yara Allen', status: 'Working', role: 'Data Analyst', email: 'yara.allen@example.com' },
  { id: 27, name: 'Zachary Young', status: 'Working', role: 'UI Designer', email: 'zachary.young@example.com' },
  { id: 28, name: 'Abigail King', status: 'Working', role: 'Product Manager', email: 'abigail.king@example.com' },
  { id: 29, name: 'Benjamin Wright', status: 'Working', role: 'QA Tester', email: 'benjamin.wright@example.com' },
  { id: 30, name: 'Chloe Scott', status: 'Working', role: 'DevOps Engineer', email: 'chloe.scott@example.com' },
  { id: 31, name: 'Daniel Green', status: 'Working', role: 'Software Engineer', email: 'daniel.green@example.com' },
  { id: 32, name: 'Eleanor Adams', status: 'Working', role: 'Data Analyst', email: 'eleanor.adams@example.com' },
  { id: 33, name: 'Frederick Baker', status: 'Working', role: 'UI Designer', email: 'frederick.baker@example.com' },
  { id: 34, name: 'Grace Nelson', status: 'Working', role: 'Product Manager', email: 'grace.nelson@example.com' },
  { id: 35, name: 'Henry Carter', status: 'Working', role: 'QA Tester', email: 'henry.carter@example.com' },
  { id: 36, name: 'Isabella Mitchell', status: 'Working', role: 'DevOps Engineer', email: 'isabella.mitchell@example.com' },
  { id: 37, name: 'Jacob Parker', status: 'Working', role: 'Software Engineer', email: 'jacob.parker@example.com' },
  { id: 38, name: 'Katherine Evans', status: 'Working', role: 'Data Analyst', email: 'katherine.evans@example.com' },
  { id: 39, name: 'Logan Collins', status: 'Working', role: 'UI Designer', email: 'logan.collins@example.com' },
  { id: 40, name: 'Madison Stewart', status: 'Working', role: 'Product Manager', email: 'madison.stewart@example.com' },
  { id: 41, name: 'Nathan Sanchez', status: 'Working', role: 'QA Tester', email: 'nathan.sanchez@example.com' },
  { id: 42, name: 'Owen Morris', status: 'Working', role: 'DevOps Engineer', email: 'owen.morris@example.com' },
  { id: 43, name: 'Penelope Rogers', status: 'Working', role: 'Software Engineer', email: 'penelope.rogers@example.com' },
  { id: 44, name: 'Quentin Reed', status: 'Working', role: 'Data Analyst', email: 'quentin.reed@example.com' },
  { id: 45, name: 'Riley Cook', status: 'Working', role: 'UI Designer', email: 'riley.cook@example.com' },
  { id: 46, name: 'Samuel Bell', status: 'Working', role: 'Product Manager', email: 'samuel.bell@example.com' },
  { id: 47, name: 'Tara Bailey', status: 'Working', role: 'QA Tester', email: 'tara.bailey@example.com' },
  { id: 48, name: 'Ulysses Cooper', status: 'Working', role: 'DevOps Engineer', email: 'ulysses.cooper@example.com' },
  { id: 49, name: 'Victoria Kelly', status: 'Working', role: 'Software Engineer', email: 'victoria.kelly@example.com' },
  { id: 50, name: 'Walter Howard', status: 'Working', role: 'Data Analyst', email: 'walter.howard@example.com' },
  { id: 51, name: 'Xavier Ward', status: 'Working', role: 'UI Designer', email: 'xavier.ward@example.com' },
  { id: 52, name: 'Yasmine Peterson', status: 'Working', role: 'Product Manager', email: 'yasmine.peterson@example.com' },
  { id: 53, name: 'Zachary Gray', status: 'Working', role: 'QA Tester', email: 'zachary.gray@example.com' },
  { id: 54, name: 'Abigail Ramirez', status: 'Working', role: 'DevOps Engineer', email: 'abigail.ramirez@example.com' },
  { id: 55, name: 'Benjamin James', status: 'Working', role: 'Software Engineer', email: 'benjamin.james@example.com' },
  { id: 56, name: 'Chloe Watson', status: 'Working', role: 'Data Analyst', email: 'chloe.watson@example.com' },
  { id: 57, name: 'Daniel Brooks', status: 'Working', role: 'UI Designer', email: 'daniel.brooks@example.com' },
  { id: 58, name: 'Eleanor Kelly', status: 'Working', role: 'Product Manager', email: 'eleanor.kelly@example.com' },
  { id: 59, name: 'Frederick Sanders', status: 'Working', role: 'QA Tester', email: 'frederick.sanders@example.com' },
  { id: 60, name: 'Grace Price', status: 'Working', role: 'DevOps Engineer', email: 'grace.price@example.com' },
  { id: 61, name: 'Henry Bennett', status: 'Working', role: 'Software Engineer', email: 'henry.bennett@example.com' },
  { id: 62, name: 'Isabella Wood', status: 'Working', role: 'Data Analyst', email: 'isabella.wood@example.com' },
  { id: 63, name: 'Jacob Barnes', status: 'Working', role: 'UI Designer', email: 'jacob.barnes@example.com' },
  { id: 64, name: 'Katherine Ross', status: 'Working', role: 'Product Manager', email: 'katherine.ross@example.com' },
  { id: 65, name: 'Logan Henderson', status: 'Working', role: 'QA Tester', email: 'logan.henderson@example.com' },
  { id: 66, name: 'Madison Coleman', status: 'Working', role: 'DevOps Engineer', email: 'madison.coleman@example.com' },
  { id: 67, name: 'Nathan Jenkins', status: 'Working', role: 'Software Engineer', email: 'nathan.jenkins@example.com' },
  { id: 68, name: 'Owen Perry', status: 'Working', role: 'Data Analyst', email: 'owen.perry@example.com' },
  { id: 69, name: 'Penelope Powell', status: 'Working', role: 'UI Designer', email: 'penelope.powell@example.com' },
  { id: 70, name: 'Quentin Long', status: 'Working', role: 'Product Manager', email: 'quentin.long@example.com' },
  { id: 71, name: 'Riley Patterson', status: 'Working', role: 'QA Tester', email: 'riley.patterson@example.com' },
  { id: 72, name: 'Samuel Hughes', status: 'Working', role: 'DevOps Engineer', email: 'samuel.hughes@example.com' },
  { id: 73, name: 'Tara Flores', status: 'Working', role: 'Software Engineer', email: 'tara.flores@example.com' },
  { id: 74, name: 'Ulysses Washington', status: 'Working', role: 'Data Analyst', email: 'ulysses.washington@example.com' },
  { id: 75, name: 'Victoria Butler', status: 'Working', role: 'UI Designer', email: 'victoria.butler@example.com' },
  { id: 76, name: 'Walter Simmons', status: 'Working', role: 'Product Manager', email: 'walter.simmons@example.com' },
  { id: 77, name: 'Xavier Foster', status: 'Working', role: 'QA Tester', email: 'xavier.foster@example.com' },
  { id: 78, name: 'Yasmine Gonzales', status: 'Working', role: 'DevOps Engineer', email: 'yasmine.gonzales@example.com' },
  { id: 79, name: 'Zachary Bryant', status: 'Working', role: 'Software Engineer', email: 'zachary.bryant@example.com' },
  { id: 80, name: 'Abigail Alexander', status: 'Working', role: 'Data Analyst', email: 'abigail.alexander@example.com' },
  { id: 81, name: 'Benjamin Russell', status: 'Working', role: 'UI Designer', email: 'benjamin.russell@example.com' },
  { id: 82, name: 'Chloe Griffin', status: 'Working', role: 'Product Manager', email: 'chloe.griffin@example.com' },
  { id: 83, name: 'Daniel Diaz', status: 'Working', role: 'QA Tester', email: 'daniel.diaz@example.com' },
  { id: 84, name: 'Eleanor Hayes', status: 'Working', role: 'DevOps Engineer', email: 'eleanor.hayes@example.com' },
  { id: 85, name: 'Frederick Reyes', status: 'Working', role: 'Software Engineer', email: 'frederick.reyes@example.com' },
  { id: 86, name: 'Grace Chapman', status: 'Working', role: 'Data Analyst', email: 'grace.chapman@example.com' },
  { id: 87, name: 'Henry Montgomery', status: 'Working', role: 'UI Designer', email: 'henry.montgomery@example.com' },
  { id: 88, name: 'Isabella Bailey', status: 'Working', role: 'Product Manager', email: 'isabella.bailey@example.com' },
  { id: 89, name: 'Jacob Ayala', status: 'Working', role: 'QA Tester', email: 'jacob.ayala@example.com' },
  { id: 90, name: 'Katherine Green', status: 'Working', role: 'DevOps Engineer', email: 'katherine.green@example.com' },
  { id: 91, name: 'Logan Rivera', status: 'Working', role: 'Software Engineer', email: 'logan.rivera@example.com' },
  { id: 92, name: 'Madison Cooper', status: 'Working', role: 'Data Analyst', email: 'madison.cooper@example.com' },
  { id: 93, name: 'Nathan Cook', status: 'Working', role: 'UI Designer', email: 'nathan.cook@example.com' },
  { id: 94, name: 'Owen Bell', status: 'Working', role: 'Product Manager', email: 'owen.bell@example.com' },
  { id: 95, name: 'Penelope Bailey', status: 'Working', role: 'QA Tester', email: 'penelope.bailey@example.com' },
  { id: 96, name: 'Quentin Cooper', status: 'Working', role: 'DevOps Engineer', email: 'quentin.cooper@example.com' },
  { id: 97, name: 'Riley Kelly', status: 'Working', role: 'Software Engineer', email: 'riley.kelly@example.com' },
  { id: 98, name: 'Samuel Howard', status: 'Working', role: 'Data Analyst', email: 'samuel.howard@example.com' },
  { id: 99, name: 'Tara Ward', status: 'Working', role: 'UI Designer', email: 'tara.ward@example.com' },
  { id: 100, name: 'Ulysses Peterson', status: 'Working', role: 'Product Manager', email: 'ulysses.peterson@example.com' }
];